POST http://localhost:8081/api/auth/register
Content-Type: application/json

{
    "firstname":"Eugene",
     "email":"eugenekorir11@gmail.com", 
     "gender":"male",
     "age":24, 
     "lastname":"korir", 
     "isAdmin":false,
    "password":"Eugene123"
}

###
POST http://localhost:8081/api/auth/login
Content-Type: application/json

{
    "email":"jolan@gmail.com", 
    "password":"@Joan123"
}

###
POST http://localhost:8081/api/auth/me
Content-Type: application/json 
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImpvbGFuQGdtYWlsLmNvbSIsImlkIjoiNGRmOWZmN2YtYTliYS00MmY5LTliMmUtZWQyOTAyMzgxZDI2IiwiaXNBZG1pbiI6dHJ1ZSwiaWF0IjoxNjM5MDQxODgyLCJleHAiOjE2MzkxMjgyODJ9.HlNyVpxGElLXDUMRxxD95nHLdf9kKSd_jSs0VunDOAk

{
    "email":"caleb@gmail.com"
}

###

POST http://localhost:8081/api/auth/reset-password
Content-Type: application/json 

{
    "token": "72c38a21-e66a-4b45-a8f5-e442d9b915bb",
    "password":"@Caleb123"
}

###

POST http://localhost:8081/api/auth/forgot-password
Content-Type: application/json 

{
   "email":"caleb@gmail.com"
}

###

GET http://localhost:8081/api/auth

###

GET http://localhost:8081/api/auth/72c38a21-e66a-4b45-a8f5-e442d9b915bb

###

PUT http://localhost:8081/api/auth
Content-Type: application/json

{
    "id":"72c38a21-e66a-4b45-a8f5-e442d9b915bb",
    "firstname": "jonathan",
    "lastname": "mwaniki",
    "email":"jonathan@gmail.com",
    "gender":"male",
    "age":"100"    
}

###

PUT http://localhost:8081/api/auth/delete
Content-Type: application/json

{
    "email":"jonathan@gmail.com"   
}
