POST http://localhost:8081/api/auth/register
Content-Type: application/json

{
    "firstname":"denis",
     "email":"denis11@gmail.com", 
     "gender":"male",
     "age":"40", 
     "lastname":"wambui", 
     "isAdmin":false,
    "password":"@Denis123"
}

###
POST http://localhost:8081/api/auth/login
Content-Type: application/json

{
    "email":"denis@gmail.com", 
    "password":"@Denis123"
}

###
POST http://localhost:8081/api/auth/me
Content-Type: application/json 
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImNhbGViQGdtYWlsLmNvbSIsImlkIjoiZGYwNDEwYmUtZjI3Ny00Zjc5LWI5MDMtNzVmOGIzMjNjYTAwIiwiaXNBZG1pbiI6dHJ1ZSwiaWF0IjoxNjM4NDI3NDg0LCJleHAiOjE2Mzg1MTM4ODR9.4Nxtgz3twNYy0z2_7e-ahSKAP6C2NsCeKJ7h3uFp_aA

{
    "email":"caleb@gmail.com"
}

###

POST http://localhost:8081/api/auth/reset-password
Content-Type: application/json 

{
    "token": "72c38a21-e66a-4b45-a8f5-e442d9b915bb",
    "password":"@Caleb123"
}

###

POST http://localhost:8081/api/auth/forgot-password
Content-Type: application/json 

{
   "email":"caleb@gmail.com"
}

###

GET http://localhost:8081/api/auth

###

GET http://localhost:8081/api/auth/72c38a21-e66a-4b45-a8f5-e442d9b915bb

###

PUT http://localhost:8081/api/auth
Content-Type: application/json

{
    "id":"72c38a21-e66a-4b45-a8f5-e442d9b915bb",
    "firstname": "jonathan",
    "lastname": "mwaniki",
    "email":"jonathan@gmail.com",
    "gender":"male",
    "age":"100"    
}

###

PUT http://localhost:8081/api/auth/delete
Content-Type: application/json

{
    "email":"jonathan@gmail.com"   
}
